// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: internal/grpcserver/proto/shortener.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` //  string user_id = 2;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenRequest) Reset() {
	*x = ShortenRequest{}
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenRequest) ProtoMessage() {}

func (x *ShortenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenRequest.ProtoReflect.Descriptor instead.
func (*ShortenRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpcserver_proto_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ShortenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	AlreadyExists bool                   `protobuf:"varint,2,opt,name=already_exists,json=alreadyExists,proto3" json:"already_exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenResponse) Reset() {
	*x = ShortenResponse{}
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenResponse) ProtoMessage() {}

func (x *ShortenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenResponse.ProtoReflect.Descriptor instead.
func (*ShortenResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpcserver_proto_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *ShortenResponse) GetAlreadyExists() bool {
	if x != nil {
		return x.AlreadyExists
	}
	return false
}

type ResolveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpcserver_proto_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveRequest) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type ResolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,2,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpcserver_proto_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *ResolveResponse) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *ResolveResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpcserver_proto_shortener_proto_rawDescGZIP(), []int{4}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpcserver_proto_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *PingResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ShortenBatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// string user_id = 1;
	Items         []*ShortenBatchItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenBatchRequest) Reset() {
	*x = ShortenBatchRequest{}
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchRequest) ProtoMessage() {}

func (x *ShortenBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchRequest.ProtoReflect.Descriptor instead.
func (*ShortenBatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpcserver_proto_shortener_proto_rawDescGZIP(), []int{6}
}

func (x *ShortenBatchRequest) GetItems() []*ShortenBatchItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ShortenBatchItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenBatchItem) Reset() {
	*x = ShortenBatchItem{}
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenBatchItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchItem) ProtoMessage() {}

func (x *ShortenBatchItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchItem.ProtoReflect.Descriptor instead.
func (*ShortenBatchItem) Descriptor() ([]byte, []int) {
	return file_internal_grpcserver_proto_shortener_proto_rawDescGZIP(), []int{7}
}

func (x *ShortenBatchItem) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ShortenBatchItem) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type ShortenBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ShortenBatchResult  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenBatchResponse) Reset() {
	*x = ShortenBatchResponse{}
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchResponse) ProtoMessage() {}

func (x *ShortenBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchResponse.ProtoReflect.Descriptor instead.
func (*ShortenBatchResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpcserver_proto_shortener_proto_rawDescGZIP(), []int{8}
}

func (x *ShortenBatchResponse) GetResults() []*ShortenBatchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ShortenBatchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenBatchResult) Reset() {
	*x = ShortenBatchResult{}
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenBatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchResult) ProtoMessage() {}

func (x *ShortenBatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchResult.ProtoReflect.Descriptor instead.
func (*ShortenBatchResult) Descriptor() ([]byte, []int) {
	return file_internal_grpcserver_proto_shortener_proto_rawDescGZIP(), []int{9}
}

func (x *ShortenBatchResult) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ShortenBatchResult) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type GetUserURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserURLsRequest) Reset() {
	*x = GetUserURLsRequest{}
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserURLsRequest) ProtoMessage() {}

func (x *GetUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserURLsRequest.ProtoReflect.Descriptor instead.
func (*GetUserURLsRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpcserver_proto_shortener_proto_rawDescGZIP(), []int{10}
}

type GetUserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*UserURL             `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserURLsResponse) Reset() {
	*x = GetUserURLsResponse{}
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserURLsResponse) ProtoMessage() {}

func (x *GetUserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserURLsResponse.ProtoReflect.Descriptor instead.
func (*GetUserURLsResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpcserver_proto_shortener_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserURLsResponse) GetUrls() []*UserURL {
	if x != nil {
		return x.Urls
	}
	return nil
}

type UserURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserURL) Reset() {
	*x = UserURL{}
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserURL) ProtoMessage() {}

func (x *UserURL) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserURL.ProtoReflect.Descriptor instead.
func (*UserURL) Descriptor() ([]byte, []int) {
	return file_internal_grpcserver_proto_shortener_proto_rawDescGZIP(), []int{12}
}

func (x *UserURL) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *UserURL) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type DeleteUserURLsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// string user_id = 1;
	ShortUrls     []string `protobuf:"bytes,2,rep,name=short_urls,json=shortUrls,proto3" json:"short_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserURLsRequest) Reset() {
	*x = DeleteUserURLsRequest{}
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLsRequest) ProtoMessage() {}

func (x *DeleteUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserURLsRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserURLsRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpcserver_proto_shortener_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteUserURLsRequest) GetShortUrls() []string {
	if x != nil {
		return x.ShortUrls
	}
	return nil
}

type DeleteUserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"` // always true if job enqueued successfully
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserURLsResponse) Reset() {
	*x = DeleteUserURLsResponse{}
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLsResponse) ProtoMessage() {}

func (x *DeleteUserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserURLsResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserURLsResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpcserver_proto_shortener_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteUserURLsResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type GetInternalStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInternalStatsRequest) Reset() {
	*x = GetInternalStatsRequest{}
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInternalStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInternalStatsRequest) ProtoMessage() {}

func (x *GetInternalStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInternalStatsRequest.ProtoReflect.Descriptor instead.
func (*GetInternalStatsRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpcserver_proto_shortener_proto_rawDescGZIP(), []int{15}
}

type GetInternalStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          int64                  `protobuf:"varint,1,opt,name=urls,proto3" json:"urls,omitempty"`
	Users         int64                  `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInternalStatsResponse) Reset() {
	*x = GetInternalStatsResponse{}
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInternalStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInternalStatsResponse) ProtoMessage() {}

func (x *GetInternalStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcserver_proto_shortener_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInternalStatsResponse.ProtoReflect.Descriptor instead.
func (*GetInternalStatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpcserver_proto_shortener_proto_rawDescGZIP(), []int{16}
}

func (x *GetInternalStatsResponse) GetUrls() int64 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *GetInternalStatsResponse) GetUsers() int64 {
	if x != nil {
		return x.Users
	}
	return 0
}

var File_internal_grpcserver_proto_shortener_proto protoreflect.FileDescriptor

const file_internal_grpcserver_proto_shortener_proto_rawDesc = "" +
	"\n" +
	")internal/grpcserver/proto/shortener.proto\x12\tshortener\"\"\n" +
	"\x0eShortenRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"U\n" +
	"\x0fShortenResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12%\n" +
	"\x0ealready_exists\x18\x02 \x01(\bR\ralreadyExists\"-\n" +
	"\x0eResolveRequest\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\"i\n" +
	"\x0fResolveResponse\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x02 \x01(\bR\tisDeleted\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\"\r\n" +
	"\vPingRequest\"\x1e\n" +
	"\fPingResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"H\n" +
	"\x13ShortenBatchRequest\x121\n" +
	"\x05items\x18\x02 \x03(\v2\x1b.shortener.ShortenBatchItemR\x05items\"\\\n" +
	"\x10ShortenBatchItem\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"O\n" +
	"\x14ShortenBatchResponse\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.shortener.ShortenBatchResultR\aresults\"X\n" +
	"\x12ShortenBatchResult\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\"\x14\n" +
	"\x12GetUserURLsRequest\"=\n" +
	"\x13GetUserURLsResponse\x12&\n" +
	"\x04urls\x18\x01 \x03(\v2\x12.shortener.UserURLR\x04urls\"I\n" +
	"\aUserURL\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"6\n" +
	"\x15DeleteUserURLsRequest\x12\x1d\n" +
	"\n" +
	"short_urls\x18\x02 \x03(\tR\tshortUrls\"4\n" +
	"\x16DeleteUserURLsResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\x19\n" +
	"\x17GetInternalStatsRequest\"D\n" +
	"\x18GetInternalStatsResponse\x12\x12\n" +
	"\x04urls\x18\x01 \x01(\x03R\x04urls\x12\x14\n" +
	"\x05users\x18\x02 \x01(\x03R\x05users2\xa2\x04\n" +
	"\x10ShortenerService\x12@\n" +
	"\aShorten\x12\x19.shortener.ShortenRequest\x1a\x1a.shortener.ShortenResponse\x12@\n" +
	"\aResolve\x12\x19.shortener.ResolveRequest\x1a\x1a.shortener.ResolveResponse\x127\n" +
	"\x04Ping\x12\x16.shortener.PingRequest\x1a\x17.shortener.PingResponse\x12O\n" +
	"\fShortenBatch\x12\x1e.shortener.ShortenBatchRequest\x1a\x1f.shortener.ShortenBatchResponse\x12L\n" +
	"\vGetUserURLs\x12\x1d.shortener.GetUserURLsRequest\x1a\x1e.shortener.GetUserURLsResponse\x12U\n" +
	"\x0eDeleteUserURLs\x12 .shortener.DeleteUserURLsRequest\x1a!.shortener.DeleteUserURLsResponse\x12[\n" +
	"\x10GetInternalStats\x12\".shortener.GetInternalStatsRequest\x1a#.shortener.GetInternalStatsResponseB=Z;github.com/patric-chuzhbe/urlshrt/internal/grpcserver/protob\x06proto3"

var (
	file_internal_grpcserver_proto_shortener_proto_rawDescOnce sync.Once
	file_internal_grpcserver_proto_shortener_proto_rawDescData []byte
)

func file_internal_grpcserver_proto_shortener_proto_rawDescGZIP() []byte {
	file_internal_grpcserver_proto_shortener_proto_rawDescOnce.Do(func() {
		file_internal_grpcserver_proto_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpcserver_proto_shortener_proto_rawDesc), len(file_internal_grpcserver_proto_shortener_proto_rawDesc)))
	})
	return file_internal_grpcserver_proto_shortener_proto_rawDescData
}

var file_internal_grpcserver_proto_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_internal_grpcserver_proto_shortener_proto_goTypes = []any{
	(*ShortenRequest)(nil),           // 0: shortener.ShortenRequest
	(*ShortenResponse)(nil),          // 1: shortener.ShortenResponse
	(*ResolveRequest)(nil),           // 2: shortener.ResolveRequest
	(*ResolveResponse)(nil),          // 3: shortener.ResolveResponse
	(*PingRequest)(nil),              // 4: shortener.PingRequest
	(*PingResponse)(nil),             // 5: shortener.PingResponse
	(*ShortenBatchRequest)(nil),      // 6: shortener.ShortenBatchRequest
	(*ShortenBatchItem)(nil),         // 7: shortener.ShortenBatchItem
	(*ShortenBatchResponse)(nil),     // 8: shortener.ShortenBatchResponse
	(*ShortenBatchResult)(nil),       // 9: shortener.ShortenBatchResult
	(*GetUserURLsRequest)(nil),       // 10: shortener.GetUserURLsRequest
	(*GetUserURLsResponse)(nil),      // 11: shortener.GetUserURLsResponse
	(*UserURL)(nil),                  // 12: shortener.UserURL
	(*DeleteUserURLsRequest)(nil),    // 13: shortener.DeleteUserURLsRequest
	(*DeleteUserURLsResponse)(nil),   // 14: shortener.DeleteUserURLsResponse
	(*GetInternalStatsRequest)(nil),  // 15: shortener.GetInternalStatsRequest
	(*GetInternalStatsResponse)(nil), // 16: shortener.GetInternalStatsResponse
}
var file_internal_grpcserver_proto_shortener_proto_depIdxs = []int32{
	7,  // 0: shortener.ShortenBatchRequest.items:type_name -> shortener.ShortenBatchItem
	9,  // 1: shortener.ShortenBatchResponse.results:type_name -> shortener.ShortenBatchResult
	12, // 2: shortener.GetUserURLsResponse.urls:type_name -> shortener.UserURL
	0,  // 3: shortener.ShortenerService.Shorten:input_type -> shortener.ShortenRequest
	2,  // 4: shortener.ShortenerService.Resolve:input_type -> shortener.ResolveRequest
	4,  // 5: shortener.ShortenerService.Ping:input_type -> shortener.PingRequest
	6,  // 6: shortener.ShortenerService.ShortenBatch:input_type -> shortener.ShortenBatchRequest
	10, // 7: shortener.ShortenerService.GetUserURLs:input_type -> shortener.GetUserURLsRequest
	13, // 8: shortener.ShortenerService.DeleteUserURLs:input_type -> shortener.DeleteUserURLsRequest
	15, // 9: shortener.ShortenerService.GetInternalStats:input_type -> shortener.GetInternalStatsRequest
	1,  // 10: shortener.ShortenerService.Shorten:output_type -> shortener.ShortenResponse
	3,  // 11: shortener.ShortenerService.Resolve:output_type -> shortener.ResolveResponse
	5,  // 12: shortener.ShortenerService.Ping:output_type -> shortener.PingResponse
	8,  // 13: shortener.ShortenerService.ShortenBatch:output_type -> shortener.ShortenBatchResponse
	11, // 14: shortener.ShortenerService.GetUserURLs:output_type -> shortener.GetUserURLsResponse
	14, // 15: shortener.ShortenerService.DeleteUserURLs:output_type -> shortener.DeleteUserURLsResponse
	16, // 16: shortener.ShortenerService.GetInternalStats:output_type -> shortener.GetInternalStatsResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_grpcserver_proto_shortener_proto_init() }
func file_internal_grpcserver_proto_shortener_proto_init() {
	if File_internal_grpcserver_proto_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpcserver_proto_shortener_proto_rawDesc), len(file_internal_grpcserver_proto_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpcserver_proto_shortener_proto_goTypes,
		DependencyIndexes: file_internal_grpcserver_proto_shortener_proto_depIdxs,
		MessageInfos:      file_internal_grpcserver_proto_shortener_proto_msgTypes,
	}.Build()
	File_internal_grpcserver_proto_shortener_proto = out.File
	file_internal_grpcserver_proto_shortener_proto_goTypes = nil
	file_internal_grpcserver_proto_shortener_proto_depIdxs = nil
}
