// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/google/uuid"
)

type UrlRedirect struct {
	OriginalUrl string `json:"original_url"`
	Short       string `json:"short"`
	IsDeleted   bool   `json:"is_deleted"`
}

type User struct {
	UserID uuid.UUID `json:"user_id"`
}

type UsersUrl struct {
	UserID uuid.UUID `json:"user_id"`
	Url    string    `json:"url"`
}
