// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context) (uuid.UUID, error)
	FindFullByShort(ctx context.Context, short string) (FindFullByShortRow, error)
	FindShortByFull(ctx context.Context, originalUrl string) (string, error)
	FindShortsByFulls(ctx context.Context, originalUrls []string) ([]FindShortsByFullsRow, error)
	GetUserByID(ctx context.Context, userID uuid.UUID) (uuid.UUID, error)
	GetUserUrls(ctx context.Context, userID uuid.UUID) ([]GetUserUrlsRow, error)
	InsertURLMapping(ctx context.Context, arg InsertURLMappingParams) error
	IsShortExists(ctx context.Context, short string) (bool, error)
	RemoveUsersUrls(ctx context.Context, arg RemoveUsersUrlsParams) error
	ResetDB(ctx context.Context) error
	SaveURLMapping(ctx context.Context, arg SaveURLMappingParams) error
	SaveUserUrl(ctx context.Context, arg SaveUserUrlParams) error
}

var _ Querier = (*Queries)(nil)
